Python_Shop/Python_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Python_Shop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

Python_Shop/order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('order/', views.create_order, name='create_order'),
]

Python_Shop/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:product_id>/<slug:product_slug>/', views.product_detail, name='product_detail'),
]

Python_Shop/cart/models.py
from django.db import models

# Create your models here.

Python_Shop/order/models.py
from django.db import models
from shop.models import Product

# Create your models here.
class Order(models.Model):
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    address = models.CharField(max_length=200)
    postal_code = models.CharField(max_length=10)
    city = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.id}'

    def get_cost(self):
        return self.price * self.quantity

Python_Shop/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    image = models.ImageField(upload_to='products/%Y/%m/%d')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

Python_Shop/cart/forms.py
from django import forms

class CartAddProductForm(forms.Form):
    quantity = forms.FloatField()

Python_Shop/order/forms.py
from django import forms

from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address', 'postal_code', 'city')

Python_Shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=int(cd['quantity']))
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = Product.objects.filter(id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart_detail.html', {'cart': cart})

Python_Shop/order/views.py
from django.shortcuts import render
from django.core.mail import send_mail

from .models import OrderItem, Order
from .forms import OrderForm
from .mail_sending import order_created_mail


from cart.cart import Cart

# Create your views here.
def create_order(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            order_created_mail(order.id)
            return render(request, 'order/created_order.html', {'order': order})
    else:
        form = OrderForm()
    return render(request, 'order/create_order.html', {'cart': cart,
                                                       'form': form})

Python_Shop/shop/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product

from cart.forms import CartAddProductForm

# PRODUCT LIST AND PRODUCT LIST BY CATEGORY
def product_list(request, category_slug=None):
    category = None
    products = Product.objects.all()

    if category_slug:
        category = Category.objects.filter(slug=category_slug)
        products = Product.objects.filter(category__in=category)

    return render(request, 'shop/product_list.html', {'products': products,
                                                      'category': category})

# PRODUCT DETAIL
def product_detail(request, product_id, product_slug):
    product = get_object_or_404(Product, id=product_id, slug=product_slug)
    cart_form = CartAddProductForm()

    return render(request, 'shop/product_detail.html', {'product': product,
                                                        'cart_form': cart_form})

Python_Shop/cart/templates/cart/cart_detail.html
{% extends 'base.html' %}

{% block title %}Python Shop Cart{% endblock %}

{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Image</th>
      <th scope="col">Product</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart %}
            <tr>
              <td><img class="bg-dark p-2" src="{{ item.product_img.url }}" width="30%" height="30%"></td>
              <td>{{ item.product_name }}</td>
              <td>{{ item.quantity }}</td>
              <td>${{ item.price }}<br>
                <a class="text-decoration-none text-danger red-hov" href="{% url 'cart:cart_remove' item.product_id %}">Remove</a>
              </td>
            </tr>
    {% endfor %}
    <tr class="bg-dark">
        <td class="text-white">Total Price</td>
        <td colspan="2"></td>
        <td class="text-white">${{ cart.get_total_price }}</td>
    </tr>
  </tbody>
</table>
<div class="container">
    <div class="row justify-content-around">
        <div class="col p-0">
            <button class="btn btn-dark mt-2 mb-2"><a class="text-decoration-none text-white" href="{% url 'shop:product_list' %}">&#8592; Continue Shopping</a></button>
        </div>
        <div class="col p-0 d-flex justify-content-end">
            <button class="btn btn-primary mt-2 mb-2"><a class="text-decoration-none text-white" href="{% url 'order:create_order' %}">Check Out</a></button>
        </div>
    </div>
</div>
{% endblock %}

Python_Shop/order/templates/order/create_order.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-6 mt-5 mb-2 border border-dark bg-dark">
                <form class="m-3" action="" method="post">
                    <div class="mb-3">
                        <label class="form-label text-white" for="firstNameInp">First Name</label>
                        <input id="firstNameInp" class="form-control" required name="first_name" type="text">
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-white" for="lastNameInp">Last Name</label>
                        <input id="lastNameInp" class="form-control" required name="last_name" type="text">
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-white" for="emailInp">Email</label>
                        <input id="emailInp" class="form-control" required name="email" type="text">
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-white" for="addressInp">Address</label>
                        <input id="addressInp" class="form-control" required name="address" type="text">
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-white" for="postalCodeInp">Postal Code</label>
                        <input id="postalCodeInp" class="form-control" required name="postal_code" type="text">
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-white" for="cityInp">City</label>
                        <input id="cityInp" class="form-control" required name="city" type="text">
                    </div>
                    
                    <p><input type="submit" value="Buy"></p>
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Python_Shop/order/templates/order/created_order.html
{% extends 'base.html' %}

{% block title %}Thank You{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-6 mt-5 mb-2 border border-dark bg-dark">
                <div class="m-2">
                    <h2 class="text-white">Thanks For Your Order</h2>
                    <p class="text-white">Thanks for shopping in our Python Shop.<br>Order ID: {{ order.id }}.<br><br>If u wanna go back to shopping click <a class="text-decoration-none" href="{% url 'shop:product_list' %}">here</a>.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Python_Shop/shop/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Python Shop{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Hind:wght@300;400;500;600&display=swap" rel="stylesheet">
    <link rel="icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5UpuzIagOr16AHXBqlF7XIMlmdra1Yhc9Jg&usqp=CAU">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      body {
        font-family: "Hind", Arial, Helvetica, sans-serif;
      }
      .red-hov:hover {
        text-decoration: dotted;
      }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a href="{% url 'shop:product_list' %}" class="navbar-brand"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5UpuzIagOr16AHXBqlF7XIMlmdra1Yhc9Jg&usqp=CAU" alt="logo" width="40" height="40"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMenu" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item me-5 ms-2">
                    <a class="nav-link active" aria-current="page" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i> Cart</a>
                  </li>
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'shop:product_list' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#"></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Category
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="{% url 'shop:product_list_by_category' 't-shirts' %}">T-Shirts</a></li>
                          <li><a class="dropdown-item" href="{% url 'shop:product_list_by_category' 'hoddies' %}">Hoddies</a></li>
                          <li><a class="dropdown-item" href="{% url 'shop:product_list_by_category' 'cups' %}">Cups</a></li>
                          <li><a class="dropdown-item" href="{% url 'shop:product_list_by_category' 'mouse-pads' %}">Mouse Pads</a></li>
                          <li><a class="dropdown-item" href="{% url 'shop:product_list_by_category' 'stickers' %}">Stickers</a></li>
                        </ul>
                      </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Contact</a>
                    </li>
                  </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>



    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

Python_Shop/shop/templates/contact.html
{% extends 'base.html' %}

<h1>Hello</h1>

Python_Shop/shop/templates/shop/product_detail.html
{% extends 'base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
            <div class="col-6 mt-4 mb-2 align-items-center bg-dark">
                <div class="m-3">
                <h1 class="text-light">{{ product.name }}</h1>
                <p><img class="align-items-center" src="{{ product.image.url }}" alt="" width="70%" height="70%"></p>
                {% if product.category.name == 'T-shirts' or product.category.name == 'Hoddies' %}
                    <div class="dropdown mb-2 dropend">
                        <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuBtn" data-bs-toggle="dropdown" aria-expanded="false">
                            Check Size
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuBtn">
                            <li class="dropdown-item">S</li>
                            <li class="dropdown-item">M</li>
                            <li class="dropdown-item">L</li>
                            <li class="dropdown-item">XL</li>
                            <li class="dropdown-item">XXL</li>
                        </ul>
                    </div>
                {% endif %}
                <p class="text-white-50">{{ product.description }}</p>
                <h3 class="text-light">${{ product.price }}</h3>
                <div class="row">
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        <div class="col-2">
                            <input class="form-control" name="quantity" type="text" placeholder="0">
                        </div>
                        <div class="col">
                            {% csrf_token %}
                            <input class="form-control mt-2 bg-secondary border-0" type="submit" value="Add To Cart">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

Python_Shop/shop/templates/shop/product_list.html
{% extends 'base.html' %}

{% block title %}
    {% if category %}Python Shop {{category.name}} {% else %}Python Shop {% endif %}
{% endblock %}

{% block content %}
<div>
    <h1 class="justify-content-center p-auto pt-5 pb-3">{% if category %}{{ category.0 }}{% else %}Products{% endif %}</h1>
    <div class="row col-xs-2 col-12 d-flex justify-content-around p-auto">
        {% for product in products %}
            <div class="card m-2 bg-dark" style="width: 20rem;">
                <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" class="card-img-top p-2"></a>
              <div class="card-body">
                  <a class="text-decoration-none text-white-50" href="{{ product.get_absolute_url }}"><h5 class="card-title">{{ product.name }}</h5></a>
                  <p class="card-text text-white">${{ product.price }}</p>
              </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}